### ISSUE TITLE
The plugin prevents submission decline

### ISSUE THREAD

**Issue by asrarahmadehsan** [prechelt/ojs-rqcplugin#1]
The following error is thrown when declining submission.

`
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to RqcCall::call_mhs_submission() must be of the type string, null given, called in /plugins/generic/rqc/pages/RqccallHandler.inc.php on line 57 and defined in /plugins/generic/rqc/classes/RqcCall.inc.php:19, referer: https://ghalibqjournal.com/index.php/ghalibqjournal/workflow/index/137/3
 Stack trace:, referer: https://ghalibqjournal.com/index.php/ghalibqjournal/workflow/index/137/3
 /plugins/generic/rqc/pages/RqccallHandler.inc.php(57): RqcCall::call_mhs_submission('https://reviewq...', NULL, NULL, NULL, 1, 137, true), referer: https://ghalibqjournal.com/index.php/ghalibqjournal/workflow/index/137/3
 /plugins/generic/rqc/classes/EditorActions.inc.php(133): RqccallHandler->sendToRqc(NULL, 1, 137), referer: https://ghalibqjournal.com/index.php/ghalibqjournal/workflow/index/137/3
 /lib/pkp/classes/plugins/HookRegistry.inc.php(107): EditorActions->cb_recordDecision('EditorAction::r...', Array), referer: https://ghalibqjournal.com/index.php/ghalibqjournal/workflow/index/137/3
 /lib/pkp/classes/submission/action/EditorAction.inc.php(70): HookRegistry::call('EditorAction::r...', Array), referer: https://ghalibqjournal.com/index.php/ghalibqjournal/workflow/index/137/3
 /lib/pkp/controllers/modals/editorDecision/form/SendRe in ghalibqjournal.com/plugins/generic/rqc/classes/RqcCall.inc.php on line 19, referer: https://ghalibqjournal.com/index.php/ghalibqjournal/workflow/index/137/3
`

**Comment by prechelt** [comment]
Hi @asrarahmadehsan ,
the stacktrace looks like you have not set the RQC Journal ID and RQC Journal API key which the plugin needs to do its work.  
To enter those, go to the plugin settings in OJS.  
To obtain the two values, you need to register an RQC account, log in in demo mode, create a publisher, and create a journal.  
Only after entering RQC Journal ID and RQC Journal API key can the RQC plugin be expected to work.

**Comment by prechelt** [comment]
Hi @asrarahmadehsan, if you want to use RQC seriously, please send me email. I'll be happy to help!
